### ISSUE TITLE
Gnome 3.36 Messed Up Menu

### ISSUE THREAD

**Issue by regymm** [rtlewis88/Solarized-Project#15] opened 2020-03-24 08:04 UTC
I've been using the Solarized-Dark-Magenta theme, but after upgrading to gnome-shell 3.36.0 some menus are a little bit "messed up" and ugly, especially at the two places shown in the pictures.  I'm on ArchLinux, Gnome on Xorg. I tried to disable other gnome extensions but this problem remains. 
![Screenshot from 2020-03-24 15-59-08](https://user-images.githubusercontent.com/31496626/77401855-98b41380-6de8-11ea-8ce5-29e3d3f7ba92.png)
![Screenshot from 2020-03-24 15-58-45](https://user-images.githubusercontent.com/31496626/77401861-9baf0400-6de8-11ea-8711-d16704463128.png)

**Comment by rtlewis88** [comment] 2020-04-08 15:30
Sorry, I've been tied up; I have more than one of these in the wild. You will have to give me the exact master (main) theme name and version number.  Thanks.

**Comment by regymm** [comment] 2020-04-09 02:59
I'm using the Solarized-Dark-gtk-theme-colorpack branch, version 1.9.7, downloaded from https://www.gnome-look.org/p/1308808/. 
Also tried the Solarized-Dark-GNOME-Shell-2020 branch and has the same result.

**Comment by rtlewis88** [comment] 2020-04-10 05:48
Okay; I will have it looked into this weekend. Thanks for your patience.

Regards

**Comment by rtlewis88** [comment] 2020-04-13 17:07
Still waiting on a determination from team. It is not messing up anyone else's menu, thus far; so they're trying to figure out how to reproduce a bug on various systems - where one has not yet presented. I'll press them to keep at it - and will get back to you asap. Thanks again!

**Comment by rtlewis88** [comment] 2020-04-14 04:46
@Peter,

What brand of distro are you you currently having this issue with?

Thanks.

rtl

**Comment by regymm** [comment] 2020-04-14 07:03
I'm using Archlinux. But I just managed to reproduce this problem on a Ubuntu 20.04 beta LiveCD which is using Gnome 3.36. I used gnome-tweaks and solarized-dark-magenta 1.9.7. Here are the results:

![Screenshot from 2020-04-14 14-39-52](https://user-images.githubusercontent.com/31496626/79194142-a2b4b980-7e5e-11ea-9fb0-7c2956880faa.png)
![Screenshot from 2020-04-14 14-39-40](https://user-images.githubusercontent.com/31496626/79194266-db549300-7e5e-11ea-82e1-50263e1aaa5d.png)
![Screenshot from 2020-04-14 14-39-24](https://user-images.githubusercontent.com/31496626/79194270-dd1e5680-7e5e-11ea-8429-4cc18a84eb37.png)

Hope that these could help your team. 

petergu

**Comment by amithiel** [comment] 2020-04-14 16:20
Hi,
i'm on ubuntu 20.04, having the same issue, here are some screenshots too. i just grabbed the latest version of the theme, and pasted it under .themes folder.
![1](https://user-images.githubusercontent.com/848214/79248773-2f1da700-7e74-11ea-8809-baa06cc8cc18.png)
![2](https://user-images.githubusercontent.com/848214/79248782-30e76a80-7e74-11ea-8f69-e5ae09507238.png)
![3](https://user-images.githubusercontent.com/848214/79248785-31800100-7e74-11ea-86ed-f26eaa1f594b.png)

**Comment by rtlewis88** [comment] 2020-04-16 14:54
Okay, just about all the opendesktop, theme developers are running into this, on the latest 3.36 shell. I'll personally see that it is competently addressed within the next 24 hours. Thanks for your patience.

**Comment by rtlewis88** [comment] 2020-04-16 17:55
Well, after consulting with my os people, across openSUSE, Arch, and Ubuntu, I am told that 3.36 is full of the specific bugs you guys bring up here - primarily menus. It is simply not ready for prime time yet, as told to me by the best of the best. Bleeding edge openSUSE Tumbleweed, for instance, will not be upgrading to 3.36 until it is fixed by GNOME. If you are having luck with other themes, then please use them, for the time being - until they can fix the offending bugs. Run GNOME 3.36 bugs, on the net; it's all there. I wish it was on our end, so we could take care of it for you. rtl88Themes is currently the  number 1 group out there, according to the new 2020 rankings in the three top Linux magazines; so we really don't wish for you all to be having non-theme problems which still affect our themes - believe me. If it was me, I would roll back to 3.34; because too many pros contend 3.36 is not even close to being stable yet.

I'll be keeping a close eye on their progress. Best Regards you all!

**Comment by rtlewis88** [comment] 2020-04-17 04:38
Okay, The team has been rebuilding that shell, from the ground up - to try and accommodate what we are witnessing. I have the blue variant, for you to try out. It is still lacking some color enhancements, but I don't want finish those extras until you see if this takes care of the new challenges. Please let me know ASAP! We'll get the others done if this works.

[Solarized-Dark-Blue-GS_1.4.zip](https://github.com/rtlewis88/rtl88-Themes/files/4490912/Solarized-Dark-Blue-GS_1.4.zip)

**Comment by regymm** [comment] 2020-04-17 05:33
On my ArchLinux this works perfectly, every corner looks fine. Thank you very much for your effort!

**Comment by rtlewis88** [comment] 2020-04-17 07:36
@ustcpetergu, good to hear! I will put the other colors up here in a few hours. As far as the fancy color enhancements, we have added, the past several updates; you all will have to give us a few more update pushes to add that back in. Thanks again for you patience and loyalty. Regardless of some of the other theme developers giving up, I wasn't going to let this 3.36 anomaly keep us messed up for long.

**Comment by rtlewis88** [comment] 2020-04-17 12:16
Alright, all seven flavor variants, for 3.36, are now up on the wall, over at opendesktop (pling, gnome-look, etc.)

Enjoy!

**Closed as completed** 2020-04-17 23:22 UTC
